### ISSUE TITLE
PyPI wheels for common architectures

### ISSUE THREAD

**Issue by maedoc** [the-virtual-brain/tvb-gdist#12]
Nowadays Numpy Scipy can be `pip` installed from binary wheels on most architectures.  It would be nice to have that.  This can probably even be accomplished with just Travis & Appveyor (look at Numpy project for build scripts).

**Comment by liadomide** [comment]
I have included scripts for generating Wheels for Gdist with every Hudson build, on 3 different platforms.
Could I get access to Pypi gdist with user **tvb**, for adding those?

**Comment by maedoc** [comment]
Yes yes I didn’t yet have time to find or reset password. Will do asap

**Comment by liadomide** [comment]
tvb-gdist has the wheels: https://pypi.org/project/tvb-gdist/#files
Deprecated gdist package should still be removed from Pypi
