### ISSUE TITLE
licensing

### ISSUE THREAD

**Issue by djsutherland** [the-virtual-brain/tvb-gdist#14]
It looks like the original code is under the MIT license, which [requires that the license notice be included in all copies of the software](https://opensource.org/licenses/MIT), but you're not including it. You should add a license file to the repository somewhere to keep with the terms of the license.

It also looks like you've flagged the package as a whole as GPL3, but it seems that the license notice for that is only included in the header of `alternative_geodesic.py`. To package this up in conda-forge, we'd really be much happier if you made a file called `LICENSE` or `COPYING` or whatever and included it in the distributions (by adding `include LICENSE` to your `MANIFEST.in`).

**Comment by liadomide** [comment]
Thanks for point this out.

We have recently added a LICENSE file with both the GPL text (for the cython wrapper) and the original MIT text underneath.

If you think this is appropriate, we will go further and update the Pypi package also.

**Comment by djsutherland** [comment]
Looks okay to me, not that I'm a lawyer or anything. :)
