### ISSUE TITLE
Python3 support

### ISSUE THREAD

**Issue by sanjayankur31** [the-virtual-brain/tvb-gdist#20]
Hi there,

Does geodesic support python3, or is it py2 only? Py2 will be EOL soon, so we'd like to use py3 if possible.

Cheers!

**Comment by sanjayankur31** [comment]
I've run py3 builds and it seems to build just fine. Could you please double check and update the readme (and then close this ticket)?

**Comment by vciulei** [comment]
Hello, 
I'd like to use geodesic on Python 3.7, is there any update on this ticket? Thanks a bunch!

**Comment by liadomide** [comment]
The latest version of tvb-gdist in now compatible with Python 3
https://pypi.org/project/tvb-gdist/#files
