### ISSUE TITLE
Crash on small meshes

### ISSUE THREAD

**Issue by dvirginz** [the-virtual-brain/tvb-gdist#22]
The package works on the toy example you provided, but does not work on my mesh, which is only 10,000 faces and 5000 vertices.
When using the gdist library I have the following error:

Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

Here is my code (the mesh, although bigger, is the same shape and type as the toy example

`c = sio.loadmat('raw_data/TOSCA/cat0.mat')
c = c['surface'][0][0]
X = c[0]
Y = c[1]
Z = c[2]
TRIV = c[3].astype(np.int32)
vertices = np.array(zip(X, Y, Z)).astype(np.float64)
vertices = np.reshape(vertices, (vertices.shape[0], 3))
src = np.array([1], dtype=np.int32)
trg = np.array([2], dtype=np.int32)

np.random.shuffle(TRIV)

a = gdist.compute_gdist(vertices,TRIV[:5000], source_indices = src, target_indices = trg)`

**Comment by CogNewLAB** [comment]
@dvirginz ,

I am also having this same issue. 

`src = numpy.loadtxt("src_tab.txt").astype(numpy.int32)

trg = numpy.loadtxt('trg_tab.txt').astype(numpy.int32)

triangles = numpy.loadtxt("triangles_tab.txt").astype(numpy.int32)

vertices = numpy.loadtxt("vertices_tab.txt").astype(numpy.float64)
geodisic_dist =gdist.compute_gdist(vertices, triangles, source_indices = src, target_indices = trg) `

python completely breaks and boots me out of my interpreter. 

Have you had any luck with solving this issue?

**Comment by ayan-b** [comment]
@dvirginz @CogNewLAB Can you guys please upload the source files in an issue comment?

**Comment by ayan-b** [comment]
I have tested with meshes having 16k vertices and 32k faces and not getting errors. Note that the mesh should not be disconnected. It'd be really helpful if you could upload those mesh files.

**Comment by dvirginz** [comment]
I'm sorry, I'm not facing the error anymore, and it have passed more than a year, can't remember the file mentioned

**Comment by liadomide** [comment]
We close this, with can not reproduce
