### ISSUE TITLE
Add Coverage report

### ISSUE THREAD

**Issue by ayan-b** [the-virtual-brain/tvb-gdist#36]
Helpful resources:

- pytest-dev/pytest-cov#163 (comment)
- https://stackoverflow.com/a/48672858/595220
- https://cython.readthedocs.io/en/latest/src/tutorial/profiling_tutorial.html

**Comment by liadomide** [comment]
I see this had been covered in the ctypes implementation branch, but now maybe we should fix it independently in trunk directly
