### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by ezemikulan** [the-virtual-brain/tvb-gdist#51]
Hi, I think that there might be a memory leak. I have a series of locations (seeg electrodes, ~150) on a pial surface from freesurfer and I'm trying to compute a geodesical distance matrix taking all pairwise distances using a loop. I believe that memory is not being liberated when returning from each iteration, which results in the consumption of all the available memory if the number of locations is large enough. I'm using Ubuntu 18 and Python 3.6.6. I remember having the same issue when trying to use the original gdist library more than a year ago.

A simplified version of the code would be like this:

```
dist_mat = np.empty((n_channels, n_channels))
dist_mat.fill(np.nan)

# sources = list of vertices that correspond to seeg contacts

for ix_s, src in enumerate(sources):
    trg = sources[ix_s+1:]

    src = np.array([src], dtype=np.int32)
    trg = np.array(trg, dtype=np.int32)

    gdist = compute_gdist(surf[0], surf[1], src, trg)
    dist_mat[ix_s+1:,ix_s] = gdist
```
I have been able to overcome the issue by using a Pool from the multiprocessing module, which runs each call to compute_gdist (in chunks of 50) on a separate process that liberates the memory when finishing.

I'm able to do what I need but wanted to let you know as it might require fixing. Maybe it is related to https://github.com/cython/cython/issues/3046.

**Comment by ayan-b** [comment]
Hi @ezemikulan Thanks for the report!

Can you please mention the size of  `src` and `trg` so that I can reproduce with some data?

If I understand correctly we also have a function `local_gdist_matrix` for the purpose you mentioned.

**Comment by ezemikulan** [comment]
Sure, the problem occurs when I have more than ~180 elements (I have 32 GB of RAM). As I understand the function ```local_gdist_matrix``` is not suitable for my case because i computes the distance of every vertex on the surface to all vertices within a distance, and I have a sparse selection of vertices from the surface from which I want all the pairwise distances. 

As an illustration you can see here: https://github.com/iTCf/unimi_demo_dataset. The points I'm using correspond to the red spheres on the figure there (which are intracranial electrodes). For each one of the red spheres I take the closest vertex on the surface and then I want to compute the distance between all possible pairs. That's why I take the list of this vertices and then compute the distance of each one (```src``` on each iteration) will all the following ones (```trg = sources[ix_s+1:]```). Therefore the size of ```src``` on each iteration is always 1 and the size of ```trg```changes and becomes smaller on each iteration.

Let's say that I have 180 points. On the first iteration I take the first one and compute the distance to the other 179, on the following iteration i take the second one and compute the distance to the next 178, and so on. The problem arises as iterations continue and fill up the available memory.

I'm not sure if I've explained myself clearly, if not, let me know.

**Comment by ayan-b** [comment]
Understood, thank you!

**Comment by liadomide** [comment]
@ezemikulan  Indeed, the current API of tvb-gdist is not best suited for your case. But maybe we could extend its API a bit.
@ayan-b What do you think? If the time allows, could we add a new API call to compute the geodesic distance not for all vertices, but only a small subset, as it the current example?

**Comment by ayan-b** [comment]
@liadomide I think we should investigate the memory leak issue and try to fix it if it is not an issue with Cython itself and sure we can extend the API.

**Comment by ayan-b** [comment]
Hi @ezemikulan I tried to reproduce the memory leak issue using one of our surface data meshes.

```python
import numpy as np

from gdist import compute_gdist


def test_memory_leak():
    n_channels = 1082
    vertices = np.loadtxt('data/surface_data/scalp_1082/vertices.txt', dtype=np.float64)
    triangles = np.loadtxt('data/surface_data/scalp_1082/triangles.txt', dtype=np.int32)
    surf = [vertices, triangles]

    dist_mat = np.empty((n_channels, n_channels))
    dist_mat.fill(np.nan)

    sources = np.arange(0, 1082, 1)

    for ix_s, src in enumerate(sources):
        trg = sources[ix_s+1:]

        src = np.array([src], dtype=np.int32)
        trg = np.array(trg, dtype=np.int32)

        gdist = compute_gdist(surf[0], surf[1], src, trg)
        dist_mat[ix_s+1:,ix_s] = gdist
        print(gdist)
    print(dist_mat)

test_memory_leak()

```

However, I am not able to reproduce the issue. I am using Python 3.6.9 on Ubuntu 18.04 (WSL). The data used above is available [here](https://github.com/the-virtual-brain/tvb-gdist/tree/trunk/data/surface_data/scalp_1082). Please let me know if I am doing something wrong. Also, it'd be very helpful if you can point me to the actual dataset (if it is public).

**Comment by ezemikulan** [comment]
HI @ayan-b, I have tested it with the files and the code you posted and I still see the issue. However it does not consume all the available memory before ending, it reaches the end of the loop, but the memory is still not released. I'm using _htop_ to monitor memory usage and I can see it accumulating and remaining up until i restart the kernel. I believe this is because of the size of the surface, the one you posted has 1082 vertices, while the one i'm using has 130300 (two orders of magnitude bigger). If you keep track of the memory consumption you might be able to reproduce the issue (unless it is a problem with my setup), or you can use one of Freesurfer surfaces like lh.pial. The dataset I'm using is not public but you can find an equivalent surface [here](https://gin.g-node.org/ezemikulan/Localize-MI/src/master/derivatives/sourcemodelling/sub-01/anat/sub-01_hemi-R_pial.surf.gii).

**Comment by ayan-b** [comment]
Hi @ezemikulan thank you so much!

I monitored the memory usage and can confirm that the memory is not freed after each iteration. Here's a graph that says memory usage keep getting increased:
![Screenshot from 2020-07-23 20-36-26](https://user-images.githubusercontent.com/29725587/88303349-8e693e00-cd24-11ea-97e0-8a0039ae8eaf.png)

**Comment by ayan-b** [comment]
Hi @ezemikulan here's an attempt in fixing the issue: https://github.com/the-virtual-brain/tvb-gdist/pull/53

Although it does need some clean-up, I'd be really grateful if you can please check with the original data to see if it actually fixes the issue.

You can install it in a new virtualenv by:

```shell
pip install git+https://github.com/ayan-b/tvb-geodesic@fix-memory-leak
```

Then use the `compute_gdist_lite` function. Like:

```python
import numpy as np

from gdist import compute_gdist_lite


def test_memory_leak():
    n_channels = 1082
    vertices = np.loadtxt('data/surface_data/scalp_1082/vertices.txt', dtype=np.float64)
    triangles = np.loadtxt('data/surface_data/scalp_1082/triangles.txt', dtype=np.int32)
    surf = [vertices, triangles]

    dist_mat = np.empty((n_channels, n_channels))
    dist_mat.fill(np.nan)

    sources = np.arange(0, 1082, 1)

    for ix_s, src in enumerate(sources):
        trg = sources[ix_s+1:]

        src = np.array([src], dtype=np.int32)
        trg = np.array(trg, dtype=np.int32)

        gdist = compute_gdist_lite(surf[0], surf[1], src, trg)
        print(gdist.shape[0])
        dist_mat[ix_s+1:,ix_s] = gdist
    print(dist_mat)

test_memory_leak()
```

**Comment by ezemikulan** [comment]
Hi @ayan-b , I've just tested it, it does fix the issue, great job, thanks!

**Comment by ayan-b** [comment]
Thanks for the confirmation @ezemikulan! By the way, can you please tell me what is the process called that you mentioned in the second comment so that we can have an API exposed for it?

> Let's say that I have 180 points. On the first iteration I take the first one and compute the distance to the other 179, on the following iteration i take the second one and compute the distance to the next 178, and so on. The problem arises as iterations continue and fill up the available memory.

**Comment by ezemikulan** [comment]
I would call it pairwise distance matrix or distance matrix between selected points. In fact I think that it would be great if the function could receive a selection of vertices, compute the distance between all pairs and return a matrix. I'm doing it manually, and calculating the distance in that ```(n-1)```fashion to avoid computing the same pair twice (given that the distance from _a_ to _b_ is equal to _b_ to _a_). In the loop I was just filling the lower triangle of the matrix.
