### ISSUE TITLE
Improve Code Coverage

### ISSUE THREAD

**Issue by ayan-b** [the-virtual-brain/tvb-gdist#57]
We have a couple of lines out of coverage: https://codecov.io/gh/the-virtual-brain/tvb-gdist/src/f19b70e431867bebee8693b6ae807807b8e0c335/gdist.pyx.

**Comment by liadomide** [comment]
The latest coverage report seems to measure coverage only on  `gdist.pyx`. Is this the case?
If so, could we include also files from under `geodesic_library` ?
`geodesic_utils.h` for example in #49 contains critical code and it will be interesting to know what lines are checked by the current unit-tests there.

**Comment by ayan-b** [comment]
> 
> 
> The latest coverage report seems to measure coverage only on `gdist.pyx`. Is this the case?
> If so, could we include also files from under `geodesic_library` ?
> `geodesic_utils.h` for example in #49 contains critical code and it will be interesting to know what lines are checked by the current unit-tests there.

That will require a cpptest framework. [Google test](https://github.com/google/googletest) seems to be the most popular one.
