### ISSUE TITLE
gdist_local_connectivity asymmetric

### ISSUE THREAD

**Issue by jescab01** [the-virtual-brain/tvb-gdist#80]
Dear all,

I am using the tvb-gdist package to compute the local_connectivity over a mesh that I created. The algorithm works fine and creates the sparse matrices of local connectivity. However, I have observed that the eventual matrix is not symmetrical.

I am computing the local connectivity using:

`cx = cortex.Cortex.from_file(source_file="cortical_surface.zip",
                             region_mapping_file="region_mapping.txt",
                             local_connectivity_file=None)  
`

`cx.local_connectivity = local_connectivity.LocalConnectivity(cutoff=40.0, surface=cx.region_mapping_data.surface, equation=equations.Gaussian(parameters=dict(amp=1, sigma=1, midpoint=0, offset=0)))
`

Do you know how could that be the case? I have tested with two meshes of 8k and 17k vertices. I attach the [data.zip](https://github.com/the-virtual-brain/tvb-gdist/files/14882640/data.zip) with the 8k mesh (cortical_surface.zip and region_mapping.txt) and the generated sparse matrix (local_connectivity-amp1sig1.mat).

Note: the surface is an open mesh that covers only cortical regions, the rest of the mesh (mostly subcortical) was removed.

Thanks in advance,

**Comment by jescab01** [comment]
Update: I have also tried to compute the local connectivity with a closed (spherical) surface, and the asymmetry is still there.

**Comment by liadomide** [comment]
Hi @jescab01 
Have you seen this older comment about asymmetry https://github.com/the-virtual-brain/tvb-gdist/issues/21#issuecomment-640880690 ?
Could it be the same situation in your case also ?

**Comment by jescab01** [comment]
Hi @liadomide,

Thanks for the link, I had not read it. 

Actually, the differences are relatively small, so I guess they can be due to a limited precision in the computation.

Thanks again,

**Comment by liadomide** [comment]
@jescab01 Thanks for testing and looking into this youself!
Is then ok if we close this issue?

**Comment by jescab01** [comment]
Yes, thank you.
